### PR TITLE
Set Item Commands only when Protocol

### PR DESCRIPTION
**Pull request by dcvz**
At the moment the player always tries to set remote commands based on the item.. however the player also has methods in which you can update it yourself. which can create conflict if you're trying to manage the remote actions manually.

Therefore, I've set it to use the item commands only if you've implemented the protocol in your item. Which acts an explicit intent to control commands via the item and also doesn't interfere with you if you're trying to set them manually.

### CODE REVIEW

**Comment by jorgenhenrichsen** [comment]
Thanks again for contributing 🥇.
 
The `AudioPlayer` does this already:
The way the `enableRemoteCommands(forItem:)` works now is that it checks if the `AudioItem` is `RemoteCommandable`, if it is then the remote commands supplied by the item is used. If not, then the remote commands set in the `remoteCommands` property of the `AudioPlayer` will be used, which is by default empty. This way developers can supply default remote commands if wanted, but if none are supplied then remote commands will only be applied to items conforming to `RemoteCommandable`.

Doing it as you have done here will disable the `remoteCommands` property of the `AudioPlayer` completely.

**Comment by wodka** [comment]
:/ based on how the code looks right now it will always activate remote commands.

https://github.com/jorgenhenrichsen/SwiftAudio/blob/09a7548f3ac90e2362faa3e27bcff6fbc75830f4/SwiftAudio/Classes/AudioPlayer.swift#L217-L228

**Comment by curiousdustin** [comment]
@jorgenhenrichsen, I'm revisiting this as well.

I'm using `react-native-track-player` that @dcvz is working on above.

It seems like re-enabling the commands each time is causing a strange behavior.

If I leave it like you have it, shown in the previous comment, the commands get re-enabled, BUT the next track will not play.

Oddly, the only thing I have to change to get the next track to play properly, is to implement @dcvz 's change, to basically stop the remote commands from being changed.

This odd behavior only occurs while the app is backgrounded / lock screen.

I can't figure out why this affects playback.

The next track loads, but does not play.

**Comment by curiousdustin** [comment]
@wodka , can you elaborate on what you're getting at? 

I agree, it seems like the current code WILL ALWAYS (re)enable the provided commands, even if the track items do not have the commands themselves.

Are you saying this is good or bad?

**Comment by curiousdustin** [comment]
Ok, I have determined that my particular issue is because I am doing this:

``` swift
        player.automaticallyPlayNextSong = false

        player.event.playbackEnd.addListener(self) { [weak self] reason in
            guard let `self` = self else { return }
            if reason == .playedUntilEnd {
                // Do other things that need to happen in correct order
                // ...
                // go to next track
                try? self.player.next() 
                }
            }
        }
```

Why would this cause the player to go to the next track, load it, but not actually play?

**Comment by wodka** [comment]
I am using it through https://github.com/react-native-kit/react-native-track-player

During runtime the remote commands are enabled there, and without the change they are never fired. With the condition to only change the RemoteCommand if there is a configuration passed for it, it starts to work!

right now I'm using a patch to always apply this change:
```
diff --git a/node_modules/react-native-track-player/ios/RNTrackPlayer/Vendor/AudioPlayer/SwiftAudio/Classes/AudioPlayer.swift b/node_modules/react-native-track-player/ios/RNTrackPlayer/Vendor/AudioPlayer/SwiftAudio/Classes/AudioPlayer.swift
index e9cb292..6f5649e 100755
--- a/node_modules/react-native-track-player/ios/RNTrackPlayer/Vendor/AudioPlayer/SwiftAudio/Classes/AudioPlayer.swift
+++ b/node_modules/react-native-track-player/ios/RNTrackPlayer/Vendor/AudioPlayer/SwiftAudio/Classes/AudioPlayer.swift
@@ -169,7 +169,9 @@ public class AudioPlayer: AVPlayerWrapperDelegate {
         if (automaticallyUpdateNowPlayingInfo) {
             self.loadNowPlayingMetaValues()
         }
-        enableRemoteCommands(forItem: item)
+        if (item is RemoteCommandable) {
+            enableRemoteCommands(forItem: item)
+        }
     }
```

**Pull request closed without merging**
